name: PULL REQUEST TARGET

on:
  pull_request_target:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "Hello World"
